### ISSUE TITLE
Recent intermittent failures

### ISSUE THREAD

**Issue by samth** [racket/racket-ci#1]
Collected from http://drdr.racket-lang.org and other CI. Omits DrRacket errors that have been ongoing for a long time.

- [x] http://drdr.racket-lang.org/53478/cs/pkgs/racket-test-extra/tests/future/random-future.rkt
- [x] http://drdr.racket-lang.org/53475/cs/racket/share/pkgs/math-test/math/tests/flonum-tests.rkt
- [x] http://drdr.racket-lang.org/53473/cs/racket/share/pkgs/gui-test/tests/gracket/tmp97 (this is a DrDr bug, maybe)
- [x] http://drdr.racket-lang.org/53456/pkgs/racket-test/tests/future/future.rkt
- [x] http://drdr.racket-lang.org/53488/cs/racket/share/pkgs/typed-racket-test/tr-random-testing.rkt http://drdr.racket-lang.org/53579/cs/racket/share/pkgs/typed-racket-test/tr-random-testing.rkt
http://drdr.racket-lang.org/53440/cs/racket/share/pkgs/typed-racket-test/tr-random-testing.rkt https://github.com/racket/typed-racket/pull/899/checks?check_run_id=391995156 
 (these are all TR random testing, but the seeds to not reproduce the errors)
- [x] http://drdr.racket-lang.org/53572/cs/pkgs/racket-test/tests/future/shutdown-stress.rkt (too old to debug, see #3).
- [x] https://travis-ci.org/racket/racket/jobs/632013183#L8786 (code no longer available in PR)
- [x] http://drdr.racket-lang.org/53580/racket/share/pkgs/redex-examples/redex/examples/delim-cont/randomized-tests.rkt (see #3)
- [x] http://drdr.racket-lang.org/53847/racket/share/pkgs/games/gobblet/robot.rkt (very old bug that no one has ever found/fixed)
- [x] http://drdr.racket-lang.org/54117/pkgs/racket-test/tests/file/packers.rkt (has been happening for a long time)

**Comment by samth** [comment]
Things to do here:
- open separate issues
- try to replicate these bugs
- create a smaller test case

**Comment by samth** [comment]
cc @jackfirth @pmatos

**Comment by pmatos** [comment]
Apologies - I had forgotten about this issue until I saw the reference to it on https://github.com/racket/racket/commit/1d383863d465598aaaa70a3423ff6c61a1bfbabb .

I was stalled on an urgent work task for quite a few weeks in the beginning of 2020 but I am finally freer. I was working on porting features from gitlab so we can have an 100% Actions CI.

At the same time, I am slighly concerned that recently actions started (for no good reason) to deprovision our machines mid-job. Like in: https://github.com/racket/racket/runs/454699475?check_suite_focus=true

**Comment by pmatos** [comment]
Another thing I want to understand - which I don't at the moment is exactly how tests in DrDr are ran. We don't currently see any failures on our tests, so if there are more tests we can run, we should add them to the CI script.

**Comment by pmatos** [comment]
For CI specific issues / features we want in the system should we open the issues here or in `racket/racket`?

**Comment by samth** [comment]
I think general planning makes sense here but if there's something specific for the racket/racket repo it belongs there.

**Comment by samth** [comment]
The command line is on the page in drdr results. DrDr runs all the files in the distribution, roughly. The about page has more details.  It's about 20 hours of compute per run.

**Comment by pmatos** [comment]
> At the same time, I am slighly concerned that recently actions started (for no good reason) to deprovision our machines mid-job. Like in: https://github.com/racket/racket/runs/454699475?check_suite_focus=true

I went ahead and submitted an incident report to GitHub.

**Comment by pmatos** [comment]
> I think general planning makes sense here but if there's something specific for the racket/racket repo it belongs there.

Sure!

**Comment by pmatos** [comment]
> The command line is on the page in drdr results. DrDr runs all the files in the distribution, roughly. The about page has more details. It's about 20 hours of compute per run.

Wow - 20hours? I will try it on my server and see if it is any better. In any case we should probably run it on a regular basis - possibly on a schedule.

Given a job cannot run for 20hours on a normal github actions vm, I can provision my server for this purpose.

**Comment by samth** [comment]
Yes, it's a lot, especially now that it does everything twice, once for traditional racket and once for CS. We have a dedicated machine here at IU running it, which is a lot cheaper than the cloud for this.

**Comment by pmatos** [comment]
> The command line is on the page in drdr results. DrDr runs all the files in the distribution, roughly. The about page has more details. It's about 20 hours of compute per run.

That command line is for a single file but where's the log for the whole run? For example, in drdr source I see:
`(notify! "Removing checkout directory: ~a" co-dir)` in https://github.com/racket/drdr/blob/a68107aec2ac512d44b0d80b239f9c91c7030216/plt-build.rkt#L37

Where is this string? Is it just a local machine file? Would you be able to send me a copy of a recent run log please?

**Comment by samth** [comment]
https://github.com/racket/racket/commit/dbaf9a88604310b00ef0f38ce5678e8b19383667 attempts to fix the packers issue.

**Comment by samth** [comment]
Everything here is either not reproducible, fixed, or has an issue open, so I'm closing.
